#ifndef TCMG_READER_FAILURE_H_
#define TCMG_READER_FAILURE_H_

typedef enum {
    READER_FAILURE_NONE = 0,
    READER_FAILURE_NOT_FOUND,
    READER_FAILURE_REJECTED,
    READER_FAILURE_CARD_ERROR,
    READER_FAILURE_READER_ERROR,
    READER_FAILURE_TRANSPORT_ERROR
} E_READER_FAILURE;

#endif
