#!/usr/bin/env python3
"""
gen_assets.py — embed CSS and JS assets into a C header at build time.
Usage:
    python3 tools/gen_assets.py
Reads:
    webif/assets/tcmg.css
    webif/assets/tcmg.js
Writes:
    webif/webif_assets.h
The generated header exposes two C string literals:
    TCMG_CSS  — the stylesheet (suitable for <style> tags)
    TCMG_JS   — the JS (suitable for <script> tags; contains %d/%% printf specifiers)
Embedding method: each file is converted to a C string literal via
repr()-style escaping so that the result is a plain const char[] with
no runtime allocation.  The CSS string has no format specifiers and is
safe to pass to buf_printf() as a %s argument.  The JS string contains
intentional %d and %% markers and must be passed directly as the fmt
argument to buf_printf() (not via %s).
"""
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT       = os.path.dirname(SCRIPT_DIR)

SRC = {
    'css': os.path.join(ROOT, 'webif', 'assets', 'tcmg.css'),
    'js' : os.path.join(ROOT, 'webif', 'assets', 'tcmg.js'),
}
OUT = os.path.join(ROOT, 'webif', 'assets', 'webif_assets.h')

def to_c_string(text):
    out = []
    for ch in text:
        if ch == '\\': out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif ch == '\n': out.append('\\n')
        elif ch == '\r': out.append('\\r')
        elif ch == '\t': out.append('\\t')
        elif ch == '\0': out.append('\\0')
        else: out.append(ch)
    return ''.join(out)

def split_c_string(body, width=4000):
    chunks = []
    while body:
        chunk = body[:width]
        body  = body[width:]
        chunks.append(chunk)
    lines = []
    for i, chunk in enumerate(chunks):
        if i < len(chunks) - 1:
            lines.append(f'"{chunk}" \\')
        else:
            lines.append(f'"{chunk}"')
    return '\n'.join(lines)

def embed(name, path):
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    body  = to_c_string(text)
    lines = split_c_string(body)
    macro = name.upper()
    return f'/* {os.path.basename(path)} — {len(text)} bytes */\n#define {macro} \\\n{lines}\n'

banner = """\
/* webif_assets.h — AUTO-GENERATED by tools/gen_assets.py
 *
 * DO NOT EDIT by hand.  Run:
 *   python3 tools/gen_assets.py
 * or use:
 *   make assets
 *
 * TCMG_CSS  : full stylesheet — use as %s arg in buf_printf
 * TCMG_JS   : runtime JS     — use as format string in buf_printf
 *             (contains intentional %d / %% printf specifiers)
 */
#ifndef TCMG_WEBIF_ASSETS_H_
#define TCMG_WEBIF_ASSETS_H_

"""

footer = "\n#endif\n"

for k, p in SRC.items():
    if not os.path.exists(p):
        print(f"ERROR: source file not found: {p}", file=sys.stderr)
        sys.exit(1)

with open(OUT, 'w', encoding='utf-8') as out:
    out.write(banner)
    out.write(embed('TCMG_CSS', SRC['css']))
    out.write('\n')
    out.write(embed('TCMG_JS',  SRC['js']))
    out.write(footer)

print(f"Generated: {OUT}")
for k, p in SRC.items():
    size = os.path.getsize(p)
    print(f"  {k.upper()}: {p} ({size} bytes)")
